#define C_BLUE 0x5495FFFF // Основной цвета сервера - синий
#define C_RED 0xF45F5FFF // Красный
#define C_GREEN 0x228B22FF // Зелёный
#define C_GREY 0xAFAFAFFF // Серый
#define C_WHITE 0xFFFFFFFF // белый

#define BLUE "{5495ff}" // Синий для использования в тексте и диалогах
#define RED "{f45f5f}" // Красный для использования в тексте и диалогах
#define WHITE "{ffffff}" // Белый для использования в тексте и диалогах
#define GREEN "{228B22}" // Зелёный для использования в тексте и диалогах
#define GREY "{afafaf}"// Серый для использования в тексте и диалогах
